language: haskell
ghc:
      - '7.10'
      - '7.8'

jdk:
    - oraclejdk7  # needed for local Neo4j 2.0+

env:
    # test across multiple versions of Neo4j:
    - NEO4J_VERSION="2.2.1"
    - NEO4J_VERSION="2.2.0"
    - NEO4J_VERSION="2.1.7"
    - NEO4J_VERSION="2.1.5"
    - NEO4J_VERSION="2.0.3"

before_install:
    # install Neo4j locally:
    - wget dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz
    - tar -xzf neo4j-community-$NEO4J_VERSION-unix.tar.gz
    - echo "dbms.security.auth_enabled=false" >> neo4j-community-$NEO4J_VERSION/conf/neo4j-server.properties
    - neo4j-community-$NEO4J_VERSION/bin/neo4j start

# don't CI feature branches, but note that this *does* CI PR merge commits --
# including before they're made! =)
branches:
  only:
    - master
